# Generated by Django 2.0.7 on 2018-08-01 15:55

from django.db import migrations
from ..models import Poll, Choice


def demo_data(apps, editor):
    frontend = Poll.objects.create(question_text = 'What\'s your favourite frontend framework?')    
    Choice.objects.create(question = frontend, choice_text = 'Angular', votes = 0)
    Choice.objects.create(question = frontend, choice_text = 'React', votes = 0)
    Choice.objects.create(question = frontend, choice_text = 'Vue', votes = 0)
    
    app = Poll.objects.create(question_text = 'Best name for this app?')    
    Choice.objects.create(question = app, choice_text = 'Gotta Ask \'Em All', votes = 0)
    Choice.objects.create(question = app, choice_text = 'Pollem', votes = 0)
    Choice.objects.create(question = app, choice_text = 'Votey McVoteFace', votes = 0)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(demo_data),
    ]
